
name: Java CI for test-lab01

on:
  push:
    branches: [ "Lab-01" ]
  pull_request:
    branches: [ "Lab-01" ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Build with javac
      working-directory: test-lab01
      run: |
        mkdir -p bin
        javac -cp "test-lib/junit-platform-console-standalone-1.13.0-M3.jar" -d bin $(find src -name '*.java') $(find test -name '*.java')
    - name: Test using JUnit Jupiter
      working-directory: test-lab01
      run: |
        java -jar ./test-lib/junit-platform-console-standalone-1.13.0-M3.jar execute --class-path bin --scan-class-path